image: golang:1.11-stretch

variables:
  REPO_NAME: gitlab.com/coopernurse/maelstrom

stages:
    - test

test:
    stage: test
    script:
      - make test
      - make maelctl
      - make maelstromd
      