image: coopernurse/maelstrom-build:latest
services:
  - docker:dind

variables:
  REPO_NAME: gitlab.com/coopernurse/maelstrom
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DIND_HOST: docker

before_script:
  - export CI_CACHEDIR=`pwd`/.cache
  - export GOPATH="$CI_CACHEDIR"
  - export PATH="$PATH:$CI_CACHEDIR/bin"
  - export PYTHONPATH="$CI_CACHEDIR/lib/python2.7/site-packages"
  - mkdir -p "$CI_CACHEDIR"
  - ./scripts/install_deps.sh

cache:
  paths:
    - .cache

stages:
    - test

test:
    stage: test
    script:
      - make idl
      - make test
      - make maelctl
      - make maelstromd
      