name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      shell: bash
      run: |
        set -x
        export DIND_HOST=docker
        #export DOCKER_HOST=tcp://localhost:2375
        export DOCKER_DRIVER=overlay2
        export CI_CACHEDIR=`pwd`/.cache
        export GOPATH="$CI_CACHEDIR"
        export PATH="$PATH:$CI_CACHEDIR/bin:$HOME/.local/bin"
        export PYTHONPATH="$CI_CACHEDIR/lib/python2.7/site-packages"
        mkdir -p "$CI_CACHEDIR"
        docker images
        #pip install --user wheel
        #./scripts/install_deps.sh
        #make idl
        #make test
        #make maelctl
        #make maelstromd
