name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    #- uses: docker://coopernurse/maelstrom-build:latest
    - name: Run tests
      shell: bash
      run: |
        export DIND_HOST=docker
        export DOCKER_DRIVER=overlay2
        ./scripts/install_deps.sh
        make idl
        make test
        make maelctl
        make maelstromd
