name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      shell: bash
      run: |
        set -x
        export CI_CACHEDIR=`pwd`/.cache
        export GOPATH="$CI_CACHEDIR"
        export PATH="$PATH:$CI_CACHEDIR/bin:$HOME/.local/bin"
        export PYTHONPATH="$CI_CACHEDIR/lib/python2.7/site-packages"
        export LOGXI=*=DBG
        mkdir -p "$CI_CACHEDIR"
        docker images
        env
        pip install --user wheel
        ./scripts/install_deps.sh
        sudo apt-get install -y libsqlite3-dev
        make idl
        make maelctl
        make maelstromd
        make test
